server:
  address: 0.0.0.0
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          json_format_mapper: jackson
        format_sql: true

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-username: "orthodoxer_kompass_bot"
  webhook-path: "https://orthodoxer-kompass-production.up.railway.app/webhook"
